# Reproducible and replicable data analysis

This curated list provides resources to improve the reproducibility and replicability of your data analysis. In brief, these concepts represent the ability for anyone to take your analysis and be able to replicate and reproduce all your results. These concepts have always been important but have seen increasing attention given the replicability crisis in social psychology and science more broadly. Moreover, the open science movement and the ability to use online portals such as the OSF and GitHub have made these principles easier to implement. This list also contains useful guides on how to improve record keeping, organisation, coding, cleaning, and manipulating data while at the same time producing dynamic reports that track everything you do (and all the changes) during your data analysis. This list does rely heavily on using R software, but the same principles can be applied to other statistical software packages including Stata and SPSS. I would encourage more people to make the switch to R programming (it’s not as hard as you might think). The main message is to use syntax/coding and annotate as much as possible! No more point-and-click or having to re-do tables in excel!! 

## Journal articles and textbooks
DeBruine, L., Barr, D. (2021). Data skills for reproducible research. Self-published. <https://psyteachr.github.io/reprores-v2/index.html#how-to-learn-data-skills> 

- *An excellent online textbook on how to improve your data skills with a focus on tidy data, reproducible workflows, dynamic reports, and some more advanced topics. I recommend going over chapter 2 and chapter 6. The great thing about this book is that it has several accompanying YouTube videos outlining the concepts!*

Epskamp, S. (2019). Reproducibility and Replicability in a fast-paced methodological world, Advances in Methods and Practices in Psychological Science, 2(2), 145-155.
 
- *Excellent overview of why we need reproducibility and replicability in data analysis. Provides hints and tips on how to improve reproducibility of results and selecting software to assist.*

Baumer, B., Centinkaya-Rundel, M, Bray, A., et al. (2014). R Markdown: Integrating a reproducible analysis tool into introductory statistics, Technology Innovations in Statistics Education, 8(1). https://escholarship.org/uc/item/90b2f5xh 

- *A textbook covering the basics of R markdown and how it can be applied to generate reproducible statistics.* 

De Jonge, E., van der Loo, M. (2013). An introduction to data cleaning with R. Statistics Netherlands, The Hague, NL. https://cran.r-project.org/doc/contrib/de_Jonge+van_der_Loo-Introduction_to_data_cleaning_with_R.pdf 

-	*A discussion paper outlining the basics of data cleaning in R. This paper is a little old now and might not have the most up to date methods (i.e. tidyverse).*

Buttrey, S., Whitaker, L. R. (2018). A data scientist’s guide to acquiring, cleaning, and managing data in R. Wiley & Sons: Hoboken, NJ. (See PDF for copy). 

- *A great textbook outlining the goals of data cleaning, reproducibility, basics in R, more advanced topics in R, and practical examples. I recommend going over Chapter 7 for clear examples.*

Collier, J. (2009). Using SPSS syntax a beginner’s guide. SAGE: Los Angeles, CA. <https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/1c0ug48/alma991007515259705106>

-	*A textbook for those who want to move from point-and-click to programming using syntax in SPSS… but really if you are going to the effort to learn syntax in SPSS then you are probably better off starting fresh in R.*

## Websites

<https://osf.io/>

- *For those unfamiliar with the Open Science Framework then please check out the above website. It provides a portal for store all your code, data, reports, and preprints of your work. All completely open and accessible. Please check the ethical requirements of data sharing before you share any data.* 

<https://docs.github.com/en> and <https://docs.github.com/en/get-started/quickstart/hello-world>

-	*This is an overview of GitHub. Not many people know that the Matilda Centre has a GitHub page (<https://github.com/Matilda-Centre>)! We encourage people to use GitHub to share and collaborate on analysis code. It is a great way to manage record keeping and stay on track with version control. If you want to join the Matilda Centre GitHub page then create your own profile and send me (Matt) an email with your username.* 

<https://www.povertyactionlab.org/resource/data-cleaning-and-management>

-	*Provides some useful examples and techniques for cleaning and managing data as well as ensuring proper version control and organisation.*

<https://www.rstudio.com/wp-content/uploads/2015/02/rmarkdown-cheatsheet.pdf>

-	*An R Markdown cheat sheet*

<https://finnstats.com/index.php/2021/04/02/tidyverse-in-r/> 

- *A quick guide to cleaning and manipulating using the “tidyverse”*

## Online courses/workshops

<https://reproducible-analysis-workshop.readthedocs.io/en/latest/6.RMarkdown-knitr.html>

-	*An online tutorial for using R to generate reproducible scientific analysis with a specific focus on R Markdown to generate dynamic reports.*

<https://bookdown.org/aschmi11/RESMHandbook/data-preparation-and-cleaning-in-r.html>

-	*An online course focusing on basics in R, with good examples of using the Tidyverse to clean and manipulate data.*

<https://libguides.library.kent.edu/SPSS/home>

-	*An online tutorial for working with data using SPSS. Focus on section 2 and section 3 for some nice examples of cleaning and manipulating data. It specifically draws links between the point-and-click methods of analysing data and the equivalent syntax to ease the transition.* 

<https://www.youtube.com/watch?v=Cn-72tbRNFc> 

-	*Online lecture on designing a reproducible workflow with R and Github.* 
