# Statistical Computing

In this chapter we cover some of the more commonly used statistical programs. This chapter provides introductory materials when starting to use a particular software package. In terms of getting access to these programs, you should be able to download SPSS and SAS from the University of Sydney IT services. Stata requires an individual licence, or it can be used for free remotely via the Usyd Citrix Workspace App. R and Rstudio (highly recommended) can be downloaded for free along with the many R packages (<https://www.r-project.org/> <https://rstudio.com/>). Mplus requires a license and we currently have a couple of copies of Mplus installed on the Matilda Stats computers (i.e., in Matt’s office and on the Statistics’s laptop).

## SPSS
<https://www.spss-tutorials.com/> 

-	*Website that provides online tutorials on a range of analyses in SPSS as well as the basic overview of using the program.* 

<https://libguides.library.kent.edu/SPSS/home> 

-	*Online tutorials on SPSS offered by Kent State University. Covers getting started, working with data, exploring, and analysing data.* 

<https://lo.unisa.edu.au/mod/book/view.php?id=646443&chapterid=106603> 

-	*Online tutorial offered by University of SA on SPSS. Quite good for getting started with Syntax.* 

<https://stats.idre.ucla.edu/spss/modules/> 

-	*Excellent website from UCLA on the basics of SPSS, including fundamentals, reading raw data, and data management.*

<https://milton-the-cat.rocks/dsus_oditi.html> 

-	*An awesome series of videos on the use of SPSS by Andy Field taken from his textbook “Discovering Statistics Using IBM SPSS Statistics”. I also would advise getting a copy of the textbook.  <https://amzn.asia/d/0CC4lWt>. In fact Andy Field's main website is amazing and would suggest everyone check it out <https://www.discoveringstatistics.com/>* 

<https://cce.sydney.edu.au/course/SPSS> 

-	*Formal SPSS beginner course offered online via the Usyd Centre for Continuing education. Cost involved. *

<https://www.youtube.com/playlist?list=PL7Opqhbc9Wr0GG4IZeLVO8px_e1tYYP6g> 

-	*A YouTube series on SPSS hacks.* 

<https://www.dummies.com/education/math/statistics/spss-for-dummies-cheat-sheet/> 

-	*SPSS syntax cheat sheet from the SPSS for dummies book. *

Pallant, J., (2020). SPSS survival manual: A step by step guide to data analysis using IBM SPSS (7th Edition). Routledge:

-	*A very handy textbook if you can get a copy. Companion website here <https://routledgetextbooks.com/textbooks/9781760875534/>* 

Levesque, R., (2005). SPSS programming and data management, 2nd Edition. SPSS Inc: Chicago, IL. 

-	*Textbook available here <https://spsstools.net/static/spss-programming-book/SPSS_Programming_and_Data_Management_2nd_edition.pdf>. Offers a large amount of detail in using SPSS from basics to advanced programming and macros. It is also quite helpful if you want to migrate to SAS from SPSS… but can be a little dry.* 

## Stata

https://www.stata.com/bookstore/ 

- *This link allows you to browse all the available textbooks on Stata offered via the official website.*

https://www.stata.com/bookstore/stata-journal/ 

-	*Link to the official Stata Journal that provides papers on a range of statistical topics using Stata.* 

https://stats.idre.ucla.edu/stata/ 

-	*UCLA website on the use of Stata some excellent resources including data examples, annotated output, textbook examples, and learning modules.* 

https://data.princeton.edu/stata/

-	*Stata tutorial available from Princeton University. Includes an introduction to Stata, data management, graphics, and programming.* 

https://www.stata.com/support/faqs/ 

-	*Quite a useful FAQ website offered by Stata that provides answers to questions on statistical analysis, programming, graphics, data management, etc.* 

http://www.stat.columbia.edu/~tzheng/teaching/w1111/startingstata.htm 

-	*Very brief overview on getting started with Stata offered by Columbia University.* 

https://www.stata.com/bookstore/handbook-statistical-analyses-stata/ 

-	*This book is a little old but it provides some good examples of how to carry out different data analysis procedures (e.g. logistic regression, survival analysis, GEE) in Stata.* 

## SAS

https://online.stat.psu.edu/stat480/lesson/1

-	*Penn State University online lesion on Getting started in SAS.* 

https://www.youtube.com/channel/UCWOfmTlbeesYiDJNflqsWQA 

-	*This is the SAS Users YouTube website. Official SAS trainers provide a range of video tutorials on the basics of programming and analysis using SAS. Also covers additional topics like SAS Enterprise Guide and other add-ins.* 

https://stats.idre.ucla.edu/sas/

-	*Again, excellent website from UCLA on basics of using SAS as well as an extensive list of data analysis examples, annotated outcome, textbook examples, and other useful resources. I would recommend look at the SAS Library link https://stats.idre.ucla.edu/sas/library/ as this provides an extensive range of resources.*

https://www.sas.com/store/books/categories/getting-started/cBooks-cbooks_categories-cbooks_categories_3-p1.html

-	*Official list of beginner textbooks from SAS. I would recommend “Fundamentals of Programming in SAS” and “The Little SAS Book”. You should be able to find these textbooks in the Usyd library if you search.* 

https://www.sas.com/store/books/categories/analytics-statistics/cBooks-cbooks_categories-cbooks_categories_18-p1.html 

-	*More textbooks officially endorsed by SAS but this time focused on analysis and various types of statistical procedures.* 

https://www.lexjansen.com/cgi-bin/xsl_transform.php?x=sbt&c=sugi 

- *This website provides Beginning tutorials from the SAS Global Forum (previously called SUGI). Attendees of the forum must provide papers if they are presenting and many papers demonstrate how to conduct specific analyses or tips on how to improve your SAS skills.* 

https://www.lesahoffman.com/PSYC930SAS/index.html 

-	*Some lecture materials on “Making friends with SAS” offered by Lesa Hoffman.* 

https://support.sas.com/edu/courses.html?ctry=AU 

-	*This is a link to all courses offered by SAS, some of free but the vast majority require payment and can be quite expensive but very good if you can a chance to attend one.* 

DiMaggio, C., (2013). SAS for Epidemiologists: Applications and Methods. New York, NY: Springer.

-	*A comprehensive textbook mostly designed for students studying public health and epidemiology. Covers topics such as data cleaning, programming, categorical data analysis, ANOVA, linear regression. The textbook is available online via Usyd library https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/1c0ug48/alma991019154709705106* 


## R

**Important note: R is a large and flexible program with a tonne of free resources available. This is just the tip of the iceberg and if you are wanting to use R then Google becomes your best friend. It is easy to get overwhelmed, so I suggest you start working on smaller projects and tackle tasks and topics that are suitable for that project one at a time. **

https://www.r-bloggers.com/2017/03/the-5-most-effective-ways-to-learn-r/

-	*A blog post on the most effective ways to learn R*

https://cran.r-project.org/doc/manuals/r-release/R-intro.pdf 

-*An introductory manual for R offered by the R core team.* 

http://www.r-tutor.com/r-introduction 

-	*Website that provides a series of introductory tutorials on R including basic data types, vectors, matrices, lists, data frames, and some beginning statistics.* 

https://rstudio.com/resources/webinars/a-gentle-introduction-to-tidy-statistics-in-r/

-	*A gentle introduction to Tidy Statistics.*

https://rstudio.com/collections/rstudio-essentials/ 

-	*This provides several webinars on the use of RStudio. It is highly recommended that you use R via the Rstudio software. This is a more useable interface than the base R software.* 

https://rstudio.com/resources/webinars/getting-started-with-r-markdown/

-	*This video looks at getting started with RMarkdown. This allows you to generate reproducible reports using R code.* 

https://education.rstudio.com/learn/beginner/

-	*Beginner resources that are offered by RStudio and include getting started guides, cheat sheets, textbooks, tutorials, etc. Some recommended textbooks include: R for Data science, R Cookbook, and the R Graphics Cookbook. I also highly recommend looking through the cheat sheets and picking out ones that you will most likely refer to often.*  

https://www.statmethods.net/index.html

-	*In depth website that provides tutorials for beginners in using R, including statistics, advanced statistics, graphs, and advanced graphs. *

https://www.youtube.com/user/marinstatlectures

-	*A very informative YouTube channel dedicated to statistics predominately in R *

https://www.r-graph-gallery.com/

-	*A useful website dedicated to graphing in R. It provides lots of examples for many different chart types, including graphing distributions, correlation, ranking, evolution, mapping, flow, and animated graphs.* 

https://www.r-bloggers.com/

-	*A link to many different blogs on R including new books, how to perform various statistical procedures in R, and how to improve your programming.* 

https://journal.r-project.org/ 

-	*Link to the R journal that includes papers in various R packages.* 

https://intersect.org.au/training/courses/

-	*Online Zoom lessons in R, Python and other software offered free to USyd staff. Ranges from novice to advanced topics like machine learning. I have done a course here and found it really helpful. It is great to be able to ask little questions that arise in real-time.*

https://www.sydney.edu.au/research/facilities/sydney-informatics-hub/workshops-and-training/training-calendar.html

-	*This is a calendar for the Sydney informatics hub workshops. Most are free, but some have a fee (~$500) Note some of these link to courses run by intersect.*

https://r-graphics.org/

-	*A link to the online version of the book “R Graphics Cookbook” which provides practical “recipes” for visualising data*

## Mplus

https://stats.idre.ucla.edu/mplus/ 

-	*Once more, the UCLA website this time focusing on Mplus. Provides seminars, common questions, analysis examples, textbook examples, annotated outcome.*

http://www.statmodel.com/ugexcerpts.shtml 

-	*Link to the official Mplus user’s guide and language addendums. This site also contains all the example input programs for the examples offered in each chapter of the user’s guide.* 

http://www.statmodel.com/cgi-bin/discus/discus.cgi 

-	*Official Mplus discussion forum that can sometimes be useful if you want to look for something specific. You can only post of the forum if you have an active Mplus license.* 

https://www.youtube.com/c/MplusVideos

-	*The official Mplus YouTube website that contains all the lectures and short courses on using Mplus for various statistical procedures.* 

https://www.youtube.com/playlist?list=PL8aoPJZQes3qZbWeho7WFNjgpRtLU3KHs

-	*YouTube playlist of Michael Zyphur’s Mplus workshop conducted over 5 days at the University of Melbourne. Covers a range of different topics… mostly more advanced.* 

https://www.youtube.com/user/ltolandky/videos 

-	*YouTube channel by Michael Toland. Provides several videos on introduction to Mplus, as well as specific topics on path analysis, confirmatory factor analysis, bifactor analysis, etc.* 

https://global.oup.com/us/companion.websites/9780195367621/pdf/MplusQuickGuide2015.pdf 

-	*Introductory guide in using Mplus. Provides an overview of the program, the language, some various models, and using the Mplus language generator.* 

https://cran.r-project.org/web/packages/MplusAutomation/vignettes/Vignette.pdf

-	*Highlights a very useful package in R that works with Mplus called MplusAutomation. This PDF provides some basic examples on how to start using Mplus with R. It takes advantage of the data manipulation and graphing power of R but the statistical power of the Mplus engine.*

## Comparing programs

**Important note: there is no right or wrong package to use if it can do the task that you require. Our advice would be to learn something that you feel most comfortable with using. Many people already have experience with SPSS and you can continue to use it, other people want to start fresh and might begin learning R or Mplus. The following links might help guide you in terms of which software package to start using. **

https://guides.nyu.edu/quant/statsoft 

-	*NYU comparing of different programs providing basic pros and cons of each. Covers SPSS, Stata, SAS, R and a couple of additional programs not mentioned here.* 

https://www.r-bloggers.com/2019/07/whats-the-best-statistical-software-a-comparison-of-r-python-sas-spss-and-stata/

-	*Another blog post on the different merits of each statistical program. Compares R, python, SAS, SPSS, and Stata*

https://lo.unisa.edu.au/mod/book/view.php?id=631718 

-	*Comparison of programs by University of SA.* 
