# MLM and Latent growth models

This list provides resources on multilevel models (MLM) and latent growth models for the analysis of longitudinal data. Both MLM and latent growth models are similar but different frameworks to analyse change over time. Both have strengths and weaknesses and both frameworks might be more or less suitable depending on the specific research question and the type of data that you want to analyse. Whilst MLM can be used for other types of clustered or multi-level structured data, we focus here on the use of MLM for repeated measures or longitudinal analysis.  

## Journal Articles and Textbooks

Hoffman, L. (2015). Longitudinal analysis: modelling within-person fluctuation and change. Routledge.

-	*An excellent textbook that provides easy to understand text and examples on the analysis of longitudinal data. Written primarily for non-mathematical readers. It focuses on multilevel models for longitudinal data, looking at unconditional and conditional models, time-invariant and time-varying predictors, and more advanced applications.  I have got a copy of the book if anyone wants to borrow it or it can be found online via the Usyd library website. https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/2rsddf/cdi_askewsholts_vlebooks_9781317591092 *

Duncan, T. E., Duncan, S.C., and Strycker, L. A. (2006) An introduction to latent variable growth curve modelling: concepts, issues, and application (2nd ed.) Routledge. 

-	*Another great textbook but focused more on using latent growth models for longitudinal data (also sometimes referred to as a structural equation modelling or multivariate approach to longitudinal data). Contains a range of topics including growth models for non-continuous data, growth mixture models, piecewise models, how to handle missing data, etc. This book is also available online via Usyd website. https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/2rsddf/cdi_askewsholts_vlebooks_9780203879962 *

Twisk, J. W. R. (2013). Applied longitudinal data analysis for epidemiology (a practical guide) (2nd ed.) Cambridge University Press. 

-	*A very useful textbook that provides a general overview of some of the most important techniques for longitudinal data analysis, particularly from an epidemiological data perspective. It covers multiple types of data (continuous, binary, ordinal, count), the analysis of experimental studies, and how to handle missing data. The book is available online via Usyd website. https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/2rsddf/cdi_askewsholts_vlebooks_9781107065352 *

Twisk, J. W. R. (2021) Analysis of data from randomised controlled trials: A practical guide. Springer.

- *Another useful textbook by Twisk that provides a general overview of analysis of RCTs. There are chapters that focus on using multilevel models for the analysis of RCTs with more than one follow-up measurement. The book also provides and overview of cluster RCTs and dichotomous outcomes that are commonly used in RCTs at Matilda. <https://link.springer.com/book/10.1007/978-3-030-81865-4>  *

Singer, J. D., & Willett, J. B. (2003) Applied longitudinal data analysis: modelling change and event occurrence. Oxford University Press. 

-	*Another textbook focusing on longitudinal data analysis. This book contains material on multilevel models but also on survival models. Lots of examples are provided. The book is available online via the Usyd library website. https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/2rsddf/cdi_proquest_ebookcentral_EBC3054153* 

Grimm, K. J., Ram, N., & Estabrook, R. (2016). Growth modelling: structural equation and multilevel modelling approaches. Guilford Press.

-	*Just in case you needed another textbook on growth models. This provides many real-world examples using longitudinal data. Also available online via Usyd library website https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/1c0ug48/alma991013485709705106* 

Chih‐Ping Chou, Peter M. Bentler & Mary Ann Pentz (1998) Comparisons of two statistical approaches to study growth curves: The multilevel model and the latent curve analysis, Structural Equation Modeling: A Multidisciplinary Journal, 5:3, 247-266, DOI: https://10.1080/10705519809540104 

-	*A useful paper that describes differences between multilevel modelling framework and the latent growth curve framework (sometimes called structural equation modelling or multivariate approach). Highlights the pros and cons of both frameworks depending on the needs of the analysis and the data you have. *

Curran, P. J., Obeidat, K., & Losardo, D. (2010). Twelve Frequently Asked Questions About Growth Curve Modeling. Journal of cognition and development : official journal of the Cognitive Development Society, 11(2), 121–136. https://doi.org/10.1080/15248371003699969

-	*Nice overview article of latent growth curve models. Provides an introduction, definitions, data requirements, missing data, different growth shapes, model fit, etc. *

Hesser, H. (2015). Modeling individual differences in randomized experiments using growth models: Recommendations for design, statistical analysis and reporting of results of internet interventions. Internet Interventions, 2(2), 110–120. https://doi.org/10.1016/J.INVENT.2015.02.003 

-	*Another introduction but specifically focused on RCTs and internet interventions. Particularly relevant to the work done at Matilda.*

Peugh, J. L. (2010). A practical guide to multilevel modeling. Journal of School Psychology, 48(1), 85–112. https://doi.org/10.1016/j.jsp.2009.09.002 

-	*A paper is that more generally focused on multilevel model framework. Can be applied to nested cross-sectional data or longitudinal data. Provides examples of both. *

Feingold, A. (2013). A regression framework for effect size assessments in longitudinal modelling of group differences. Review of General Psychology, 17(1), 111-121. DOI: https://doi.org/10.1037/a0030048 

-	*A paper focused on the use of estimating effect sizes associated with longitudinal growth models. Particularly relevant for identifying the magnitude of group differences (e.g., intervention data).* 

Ram, N. & Grimm, K. (2007). Using simple and complex growth models to articulate developmental change: matching theory to method. International Journal of Behavioural Development, 31(4), 303-316. https://doi.org/10.1177/0165025407077751 

-	*Another more focused paper, this time looking at non-linear models of change, e.g. quadratic, latent bias, exponential, multiphasic. *

McNeish, D., Matta, T. (2018). Differentiating between mixed-effects and latent-curve approaches to growth modeling. Behav Res 50, 1398–1414. https://doi.org/10.3758/s13428-017-0976-5

- *An excellent article outlining the similarities and differences between MLM and latent growth models as well as discussion of the strengths and weaknesses and how to select the best framework for you research question/data. *

## Websites

https://www.pilesofvariance.com/ 

- *This website accompanies the Hoffman textbook. It provides several examples in different statistical programs (SAS, SPSS, Stata, MPlus) linked to examples provided in the textbook. *

https://hedeker.people.uic.edu/ml.html

-	*Don Hedeker’s website that provides a range of examples in SPSS and SAS as well as different types of data (continuous, dichotomous, ordinal, nominal). They also provide a guide for estimating sample sizes for longitudinal designs. *

https://sites.google.com/site/longitudinalmethods/home?authuser=0 

-	*Kevin Grimm’s lab website. Contains a list of publications and downloads for example syntax and scripts. *

http://www.bristol.ac.uk/cmm/ 

-	*The centre for multilevel modelling at the University of Bristol provides a range of resources on multilevel modelling in general (not just applied to longitudinal data). *

## Online courses and videos

https://youtube.com/playlist?list=PLQGe6zcSJT0VxMZUN6DBuhIoCRZNoA2Vz   

-	*A nine-part YouTube tutorial on growth curve modelling by Curran-Bauer Analytics. Covers the basics and the differences between longitudinal analysis using multilevel modelling vs structural equation modelling.*

https://www.lesahoffman.com/PSQF7375_Longitudinal_Spring2019/index.html 

-	*Video lecture series conducted by Lesa Hoffman as part of her course at University of Iowa. *

https://youtu.be/2iQJCLiiyl8

-	*Introductory and intermediate growth models using Mplus. This lecture is part of the Mplus short course conducted at Johns Hopkins University. Lecture notes available here http://www.statmodel.com/download/Topic%203.pdf *

https://youtu.be/cr9RpSgRYVw 

-	*A three-part series explaining how to analyse longitudinal data via multilevel models in R and RStudio.* 

https://stats.idre.ucla.edu/other/mult-pkg/seminars/mlm-longitudinal/

-	*Online notes for a seminar based on Singer and Willett textbook. Focuses on comparing different analytic strategies, multilevel level models, and treatment effects over time. *
 
## Example syntax

https://stats.idre.ucla.edu/mplus/output/lgcm_mlm/ 

-	*Annotated Mplus programs on latent growth and multilevel models. Provides four examples: two growth and two multilevel models. It also draws comparisons to other programs like HLM and Stata. *

https://hedeker.people.uic.edu/ml.html

-	*Contains multiple example syntax and programs for SAS and SPSS.* 

https://stats.idre.ucla.edu/other/examples/alda/

-	*Example syntax from Singer and Willett textbook. Sample data is available to download along with programs in Mplus, SAS, Stata, R, and SPSS. *

https://sites.google.com/site/longitudinalmethods/downloads?authuser=0 

-	*Contains many example files and scripts from Mplus, SAS, OpenMX, etc. The examples come from papers published by Kevin Grimm.* 
