# Meta-analysis

This chapter provides resources that outline basic meta-analysis to summary data obtained from systematic reviews as well as more complex meta-analytic techniques such as network meta-analysis and structural equation modeling meta-analysis. There are several useful textbooks all available online that comprehensively outline the steps required for various meta-analyses. The majority of resources utilise free software packages in R to conduct meta-analyses and present results, however there are several specific software programs for meta-analysis outlined in the software section.  

## Journal Articles and Textbooks
Hedges, L. V. & Olkin, I. (2014) Statistical Method for Meta-analysis. Elsevier Science & Technology. 

-	*This is an older textbook but still very helpful. It covers the main methodological approaches for meta-analysis and provides examples in statistical packages. This book is available to view online via the Usyd library https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/1c0ug48/alma991006161679705106 *

Borenstein, M., Hedges, L. V., Higgins, J. P. T., & Rothstein, H. R. (2009) Introduction to Meta-analysis. John Wiley & Sons, Ltd. 

-	*Another fantastic starting point when learning meta-analysis. It provides a clear introduction to meta-analysis and covers the major concepts as well as provides information about identifying and avoiding common mistakes. This book is available to view online via the Usyd library https://sydney.primo.exlibrisgroup.com/permalink/61USYD_INST/1c0ug48/alma991002771109705106 * 

Harrer, M., Cuijpers, P., Furukawa, T.A., & Ebert, D.D. (2021). Doing Meta-Analysis with R: A Hands-On Guide. Boca Raton, FL and London: Chapman & Hall/CRC Press.

-	*Another very helpful and user-friendly online textbook on conducting meta-analysis with R. They cover basic topics as well as some more advanced topics like structural equation modelling meta-analysis, network meta-analysis, and Bayesian meta-analysis. One of the cooler things they have is an effect size calculator and conversion in section 17. Highly recommended resource.  https://bookdown.org/MathiasHarrer/Doing_Meta_Analysis_in_R/ * 

Field, A. P., & Gillett, R. (2010). How do to a meta-analysis. British Journal of Mathematical and Statistical Psychology, 63(3), 665-694.

-	*A great introductory paper on how to do a meta-analysis and information on how to conduct them in SPSS and R. https://doi.org/10.1348/000711010X502733 *

Paul, J., & Barari, M. (2022) Meta-analysis and traditional systematic literature reviews – what, why, when, where, and how? Psychology and Marketing, 39(6), 1099-1115.

-	*Another introductory paper on meta-analysis and how they differ from traditional systematic reviews. There is some information more specific to business research that can be ignored. *

Rouse, B., Chaimani, A., & Li, T. (2017). Network meta-analysis: an introduction for clinicians. Internal and Emergency Medicine, 12(1), 103-111. 

-	*An introduction to a relatively new technique of meta-analysis that compares multiple treatments from RCTs via the use of network analysis. Network meta-analysis is probably a large enough topic on its own so this might form its own separate list if people are interested.*

Fernandez-Castilla, B., & Van den Nootgate, W. (2023). Network meta-analysis in psychology and educational sciences: A systematic review of their characteristics. Behaviour Research Methods, 55, 2093-2108

-	*Another introductory paper on network meta-analysis but more tailored to psychological and educational research. Provides some useful warnings about what not to do when reporting a network meta-analysis.*

Deeks JJ, Higgins JPT, Altman DG (editors). Chapter 10: Analysing data and undertaking meta-analyses. In: Higgins JPT, Thomas J, Chandler J, Cumpston M, Li T, Page MJ, Welch VA (editors). Cochrane Handbook for Systematic Reviews of Interventions version 6.4 (updated August  2023). Cochrane, 2023. www.training.cochrane.org/handbook

-	*Online textbook from the Cochrane handbook of systematic reviews. Quite trustworthy and provides most reliable guidelines.*

Schwarzer, G., Carpenter, J. R., & Rucker, G. (2015). Meta-analysis with R. Springer Links. 

-	*A practical textbook outlining all the steps required to conduct a meta-analysis using the R package meta. https://github.com/guido-s/meta *

## Online courses and videos

https://www.youtube.com/watch?v=lO6s8dFBmPc 

-	*A brief introduction to meta-analysis by Daniel Lakens.* 

https://www.youtube.com/watch?v=lH4VZMTEZSc

-	*A very accessible step-by-step guide to conducting a meta-analysis using R by Daniel Quintana. Be sure to check out some of his other YouTube videos on meta-analysis and reproducible research. * 

https://www.youtube.com/watch?v=Hiu3rF5ir1U

-	*1.5hr workshop on conducting open and reproducible meta-analyses.* 

## Software

Comprehensive meta analysis https://meta-analysis.com/ 

-	*This is a software package specifically designed to meta-analysis and provides a very user friendly and systematic approach to meta-analysis. It has a wide range of support options and a long list of tutorials covering major types of meta-analysis. There is a cost to it but there are academic and student prices available. My own opinion is that if you are confident using R or another package then there is probably not much need for CMA. *

RevMan https://training.cochrane.org/online-learning/core-software/revman 

-	*This program is provided by Cochrane to assist with systematic reviews and can be used to conduct meta-analysis. It does require a subscription to use and might be useful if you want to run a systematic review and meta-analysis all within the same program.*

Metafor (R package) https://www.metafor-project.org/doku.php/metafor

-	*One of the free and open sources R packages to conduct meta-analysis. It requires some knowledge of R but there are several examples and tutorials available to conduct the analysis using metafor.*
