# Coding with AI (ChatGPT, Claude, Gemini, Co-pilot, etc)

Recent years have seen an explosion in the use of AI to assist with tasks that would usually take researchers hours to do. One task that is particularly relevant and suitable for AI assistance is statistical coding and computing. AI can take a task that would have normally taken days and complete it within a few minutes. But that doesn't mean the statistician/researcher is out of the job. In fact it is more important now to have someone who understands coding and statistics to check and make sure the code provided by the AI is doing what the researchers intend to do. Also having a good understanding of what you want to do makes generating accurate prompts for AI and easier task and less time will be required going back and forth to generate your final code and analysis. Care should also be taken when using code generated by AI given restrictions on data sharing or ethical concerns with identification of participants from sensitive data. Therefore, AI should only be used when appropriate and should avoid providing access to data. 

This chapter focuses more on the use of coding with AI in an attempt to provide some estbalished guidelines, templates, and best practices for how someone might go about incorporating AI into their workflow. As always, this is a very fast moving field and so this chapter will be regularly updated. 

## Journal Articles and Textbooks

https://www.oreilly.com/library/view/ai-assisted-statistics-for/0642572242435/ 

-*There are a number of O'Reilly books on the topic of AI-assisted statistics and data coding that are freely accessible by the University of Sydney Library. Other Examples are listed below:

https://www.oreilly.com/library/view/ai-assisted-programming/9781098164553/
https://www.oreilly.com/library/view/ai-assisted-python-for/9798341661622/
https://www.oreilly.com/library/view/coding-with-ai/9781633437272/
https://www.oreilly.com/library/view/coding-with-ai/9781394249138/

- *Have fun!